//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApproach
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSelf
    {
        public int EmployeeID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ManagerID { get; set; }
    }
}
